### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by donaldrivard** [fundacionjala/enforce-gradle-plugin#217]
Version info
OSX 10.10.5

java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)

---
## Gradle 2.6

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_21 (Oracle Corporation 23.21-b01)
OS:           Mac OS X 10.10.5 x86_64

Running gradle build I get the following error:
- What went wrong:
  java.lang.NullPointerException (no error message)
- Exception is:
  java.lang.NullPointerException
  at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:109)
  at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:323)
  at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:37)
  at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:321)
  at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2_closure5.doCall(BintrayPlugin.groovy:96)
  at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2.doCall(BintrayPlugin.groovy:88)
  at BuildAdapter1_groovyProxy.projectsEvaluated(Unknown Source)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:249)
  at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:229)
  at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
  at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:221)
  at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:209)
  at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
  at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
  at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
  at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
  at com.sun.proxy.$Proxy10.projectsEvaluated(Unknown Source)
  at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:132)
  at org.gradle.internal.Factories$1.create(Factories.java:22)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:126)
  at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
  at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
  at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
  at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
  at org.gradle.launcher.Main.doAction(Main.java:33)
  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)

BUILD FAILED

**Comment by jrojasPROS** [comment]
Hello Don, 
we're reviewing what went wrong and we'll let you know for some updates soon

Thank you for your feedback :)

Best Regards

**Comment by jrojasPROS** [comment]
Hello Don,

Please try running:
gradle init

It should generate initial files like 
- build.gradle
- gradlew
- gradlew.bat
- settings.gradle

Best Regards

**Comment by donaldrivard** [comment]
?Hi Jimmy,

I get the exact same error running gradle init. The exact same stacktrace. This is only happening when I attempt to build. Running enforce for SF CI works fine.

Don

**Comment by donaldrivard** [comment]
Found the issue. If you are using Gradle 2.4 or higher you need to change

com.jfrog.bintray.gradle:gradle-bintray-plugin:1.1

to

com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2

You can close the case

Thanks!

Don

**Comment by donaldrivard** [comment]
As a side note, this change causes all the tests for fail with the error

org.spockframework.util.InternalSpockError: Failed to instantiate spec??

Don

**Comment by donaldrivard** [comment]
Last update (<:

you also need to update spock to

org.spockframework:spock-core:1.0-groovy-2.3?

Don

**Comment by jrojasPROS** [comment]
Thanks a lot for your feedback Don, just one question, could you please mention how did you find Enforce?

Best Regards

**Comment by donaldrivard** [comment]
?It was posted on my facebook feed. Love groovy, did work with gradle in the past, and I am a salesforce architect. Perfect fit

Don
