### ISSUE TITLE
ubuntu AWS EC2 issue

### ISSUE THREAD

**Issue by donaldrivard** [fundacionjala/enforce-gradle-plugin#284]
Going through the doc I am setting up on an AWS EC2 Ubuntu instance. Here is my build.gradle file
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'org.fundacionjala.gradle.plugins.enforce:enforce-gradle-plugin:1.1.4'
    }
}

apply plugin: 'enforce'

enforce {
    srcPath = 'src'
}

running gradle tasks I am getting the error

A problem occurred evaluating root project 'test'.

> Failed to apply plugin [id 'enforce']
> Could not create task of type 'RunTestTask'.

Here is the stacktrace:
- Exception is:
  org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'test'.
      at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
      at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
      at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
      at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
      at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
      at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
      at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
      at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
      at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
      at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
      at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
      at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
      at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
      at org.gradle.internal.Factories$1.create(Factories.java:22)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
      at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
      at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
      at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
      at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
      at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
      at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
      at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
      at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
      at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
      at org.gradle.launcher.Main.doAction(Main.java:33)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'enforce']
      at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:153)
      at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
      at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
      at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
      at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
      at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
      at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
      at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
      at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
      at build_1k9upqm6hfkgl6wgzj96vlgq6.run(/home/ubuntu/test/build.gradle:11)
      at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
      ... 47 more
  Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'RunTestTask'.
      at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:123)
      at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:118)
      at org.gradle.util.GUtil.uncheckedCall(GUtil.java:401)
      at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:176)
      at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:118)
      at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:77)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:101)
      at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
      at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:62)
      at org.gradle.api.internal.project.AbstractProject.task(AbstractProject.java:935)
      at org.gradle.api.Project$task.call(Unknown Source)
      at org.fundacionjala.gradle.plugins.enforce.EnforcePlugin.apply(EnforcePlugin.groovy:49)
      at org.fundacionjala.gradle.plugins.enforce.EnforcePlugin.apply(EnforcePlugin.groovy)
      at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
      at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
      at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
      ... 57 more
  Caused by: org.gradle.internal.service.UnknownServiceException: No service of type ProgressLoggerFactory available in ProjectScopeServices.
      at org.gradle.internal.service.DefaultServiceRegistry.getServiceProvider(DefaultServiceRegistry.java:436)
      at org.gradle.internal.service.DefaultServiceRegistry.doGet(DefaultServiceRegistry.java:426)
      at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:410)
      at org.gradle.internal.service.ServiceRegistry$get.call(Unknown Source)
      at org.fundacionjala.gradle.plugins.enforce.tasks.salesforce.unittest.RunTestTask.<init>(RunTestTask.groovy:50)
      at org.fundacionjala.gradle.plugins.enforce.tasks.salesforce.unittest.RunTestTask_Decorated.<init>(Unknown Source)
      at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:56)
      at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
      at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
      ... 72 more

**Comment by JimmyRojas** [comment]
Hello @donaldrivard, thanks for use the plugin...
Let's review what went wrong and we will let you know soon

Regards,
Jimmy

**Comment by JimmyRojas** [comment]
Hello @donaldrivard,

please execute the following commands:

we would like to know about your OS gradle version:

``` groovy
gradle -version
```

In addition, to see all the available gradle's tasks:

``` groovy
gradle tasks
```

That information can help us to address the issue

Regards,
Jimmy

**Comment by StromRiddle** [comment]
I'm facing the same problem. gradle version is 4.4 . But I used wrapper to point to 2.13 which worked earlier. I also tried to change the versions of pulgin from 1.1.2 to 1.1.3 and 4 also . It din't work either. below are the gradle tasks : 

 :tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build. [incubating]
wrapper - Generates Gradle wrapper files. [incubating]

Credential Manager tasks
------------------------
addCredential - You can add a credential
showCredentials - You can obtain a credential registered
updateCredential - You can update a credential

Deployment tasks
----------------
delete - This task deploys just the files that were changed
deploy - This task deploys all the project
truncate - This task truncates classes, objects, triggers, pages, components, workflows and tabs from your code
undeploy - This task removes all components in your organization according to local repository
update - This task deploys just the files that were changed
upload - This task uploads all specific files or folders as user wants
validate - Starting validation

File Monitor tasks
------------------
reset - Reset the file monitor
status - You can display elements that were changed

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'abcd'.
components - Displays the components produced by root project 'abcd'. [incubating]
dependencies - Displays all dependencies declared in root project 'abcd'.
dependencyInsight - Displays the insight into a specific dependency in root project 'abcd'.
help - Displays a help message.
model - Displays the configuration model of root project 'abcd'. [incubating]
projects - Displays the sub-projects of root project 'abcd'.
properties - Displays the properties of root project 'abcd'.
tasks - Displays the tasks runnable from root project 'abcd'.

Package Management tasks
------------------------
installPackage - Installs a package to an organization.
uninstallPackage - Uninstalls a package from an organization.

Retrieve tasks
--------------
retrieve - This task recover specific files from an organization

Test tasks
----------
runTest - This task runs unit tests and it also generates results of unit test and coverage

Utils tasks
-----------
execute - This task executes apex code from a file or inline code

Other tasks
-----------
sonarqube - Analyzes root project 'abcd' and its subprojects with SonarQube.
unitTest

To see all tasks and more detail, run gradle tasks --all

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL

Total time: 5.101 secs

FYI : I had to point to gradle -2.13 to even get the tasks . When I try to gradlew unitTest -PcredentialId=test . I get the below error : Could not find matching constructor for :org.fundacionjala.gradle.plugins.enforce:exceptionCredentialsException(java.lang.string javax.crypto.badpadding) 

Please suggest any changes.
